[workspace.package]
authors = [ "Lachezar Kolev <lachezarkolevgg@gmail.com>" ]
description = "Ethereum indexer"
documentation = "https://docs.rs/chainthru"
edition = "2021"
homepage = "https://github.com/lbkolev/chainthru"
license = "MIT"
version = "0.1.0"
rust-version = "1.70.0"
readme = "README.md"
repository = "https://github.com/lbkolev/chainthru"

[workspace]
members = [
    "chainthru",
    "chainthru-index",
    "chainthru-server"
]

[workspace.dependencies]
chainthru-index = { path = "./chainthru-index" }
chainthru-server = { path = "./chainthru-server" }

ethereum-types = "0.14.1"
web3 = "0.19.0"
serde = "1.0.171"
serde-aux = "4.2.0"
serde_derive = "1.0.171"
sqlx = "0.7.0"
tokio = "1.29.1"
thiserror = "1.0.44"
futures = "0.3.28"
log = "0.4.19"
num_cpus = "1.16.0"
