apiVersion: v1
kind: Service
metadata:
  name: { { include "eventify-http-server.fullname" . } }
  labels: { { - include "eventify-http-server.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    { { - include "eventify-http-server.selectorLabels" . | nindent 4 } }
