[server]
port = 6969
enabled = true

[network]
enabled = true

[network.eth]
node_url = "wss://eth.llamarpc.com"
database_url = "postgres://postgres:password@localhost:5432/eventify"
mode = "stream"

[network.zksync]
node_url = "wss://mainnet.era.zksync.io/ws"
database_url = "postgres://postgres:password@localhost:5432/eventify"
mode = "stream"
